path: /home/ancheng/dataset/dataset_split
train: train/images
val: val/images
test: test/images

nc: 17
names:
  - lj
  - bd
  - heidian
  - wy
  - zyc
  - zmty
  - cq
  - zj
  - bj
  - jt
  - yy
  - bmss
  - zy
  - pd
  - HD
  - cy
  - jiaodai
